authors:
  christian-jennewein:
    name:     "Christian Jennewein"
    nickname: "Christian"
    twitter:  "cestcri"
    github:   "cestcri"
    role:     "Tech Manager"
  nicolas-schwartz:
    name:     "Nicolas Schwartz"
    nickname: "Nico"
    twitter:  "nicoschwartz"
    github:   "nicoschwartz"
    role:     "Tech Manager"
  benjamin-fraud:
    name:     "Benjamin Fraud"
    nickname: "Ben"
    role:     "Developer"

description:  "Share More, Learn More â€” BlaBlaCar's Tech team"
highlighter:  true
markdown:     rdiscount
name:         "BlaBlaTech Blog"
paginate:     10
permalink:    /blog/:title
url:          "http://blablatech.com"

gems:
  - jekyll-redirect-from
