articletags:
  - application-architecture
  - conferences
  - culture
  - organisation
  - technology

authors:
  alexandra-tritz:
    name:       "Alexandra Tritz"
    nickname:   "Lexou"
    github:     "tritzalexandra"
    twitter:    "lexouthirteen"
    role:       "Mobile Development Engineer"
  benjamin-fraud:
    name:       "Benjamin Fraud"
    nickname:   "bench1ps"
    github:     "bench1ps"
    twitter:    "bench1ps"
    role:       "Web Development Engineer"
  christian-jennewein:
    name:       "Christian Jennewein"
    nickname:   "Christian"
    twitter:    "cestcri"
    github:     "cestcri"
    role:       "Tech Manager"
  erwann-robin:
    name:       "Erwann Robin"
    nickname:   "Erwann"
    twitter:    "diwann"
    github:     "diwann"
    role:       "Mobile Development Engineer"
  fx-oxeda:
    name:       "François-Xavier Oxeda"
    nickname:   "FX"
    twitter:    "DEIONaLiMs"
    github:     "DEIONaLiMs"
    role:       "Mobile Development Engineer"
  jb-favre:
    name:       "Jean-Baptiste Favre"
    nickname:   "JB"
    twitter:    "jbfavre"
    github:     "jbfavre"
    role:       "Web Architect"
  matthieu-moquet:
    name:       "Matthieu Moquet"
    nickname:   "Mattketmo"
    github:     "MattKetmo"
    twitter:    "MattKetmo"
    role:       "Web Development Engineer"
  mickael-rodrigues:
    name:       "Mickael Rodrigues"
    nickname:   "Mickael"
    github:
    twitter:
    role:       "Mobile Development Engineer"
  nicolas-blanc:
    name:       "Nicolas Blanc"
    nickname:   "Jardin"
    twitter:    "thewhitegeek"
    github:
    role:       "Web Architect"
  nicolas-menoux:
    name:       "Nicolas Menoux"
    nickname:
    twitter:    "nickyinthecloud"
    github:
    role:       "Head of Data"
  nicolas-schwartz:
    name:       "Nicolas Schwartz"
    nickname:   "Nico"
    twitter:    "nicoschwartz"
    github:     "nicoschwartz"
    role:       "Tech Manager"
  nicolas-tricot:
    name:       "Nicolas Tricot"
    nickname:   "ShoLine"
    twitter:    "sholine42"
    github:     "sholine"
    role:       "Tech Manager"
  olivier-dolbeau:
    name:       "Olivier Dolbeau"
    nickname:   "Olivier"
    github:     "odolbeau"
    twitter:    "odolbeau"
    role:       "Web Architect"

description:    "Share More, Learn More — BlaBlaCar's Tech team"

gems:
  - jekyll-redirect-from

highlighter:    pygments

markdown:       rdiscount

name:           "the BlaBlaTech Blog"

paginate:       10

permalink:      /blog/:title

talks:
  2015:
    scrumday-2015:
      authors:  [christian-jennewein, nicolas-tricot]
      date:     "2-3 April"
      event:    "ScrumDay"
      place:    "Disneyland (France)"
      title:    "Scrum @ BlaBlaTech"
      thumb:    christian-jennewein_scrumday-2015.jpg
      url:      https://speakerdeck.com/cestcri/scrum-at-blablatech
  2014:
    symfonycon-2014:
      authors:  [matthieu-moquet]
      date:     "27-29 November"
      event:    "SymfonyCon"
      place:    "Madrid (Spain)"
      title:    "Localization should not be a pain (anymore)"
      thumb:    matthieu-moquet_symfonycon-2014.jpg
      url:      https://speakerdeck.com/mattketmo/localization-should-not-be-a-pain-anymore
    appdays-2014:
      authors:  [erwann-robin, fx-oxeda]
      date:     "6-7 November"
      event:    "appdays"
      place:    "Paris (France)"
      title:    "Comment migrer 10 millions de membres d’une webview vers une app native ?"
      thumb:    erwann-robin_appdays-2014.jpg
      url:      /talks/erwann-robin_appdays-2014.pdf
    elasticsearch-feedback:
      authors:  [nicolas-blanc, olivier-dolbeau]
      date:     "25 September"
      event:    "Meetup Elasticsearch France #9"
      place:    "Paris (France)"
      title:    "ElasticSearch feedback"
      thumb:    nicolas-blanc_elasticsearch-feedback.png
      url:      /talks/nicolas-blanc_elasticsearch-feedback.odp
    laisse-pas-trainer-ton-log:
      authors:  [olivier-dolbeau]
      date:     "23-24 October"
      event:    "Forum PHP"
      place:    "Montrouge (France)"
      title:    "Laisse pas trainer ton log"
      thumb:    olivier-dolbeau_laisse-pas-trainer-ton-log.jpg
      url:      https://speakerdeck.com/odolbeau/laisse-pas-trainer-ton-log
    when-monolog-meet-elk:
      authors:  [olivier-dolbeau]
      date:     "15 July"
      event:    "sfPot"
      place:    "Paris (France)"
      title:    "When Monolog meet ELK"
      thumb:    olivier-dolbeau_when-monolog-meet-elk.jpg
      url:      https://speakerdeck.com/odolbeau/when-monolog-meet-elk
    asynchronous-tasks-in-php:
      authors:  [olivier-dolbeau]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "Asynchronous tasks in PHP"
      thumb:    olivier-dolbeau_asynchronous-tasks-in-php.jpg
      url:      https://speakerdeck.com/odolbeau/asynchronous-tasks-in-php
    doctrine-lexer-use-case:
      authors:  [olivier-dolbeau]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "Doctrine Lexer use case"
      thumb:    olivier-dolbeau_doctrine-lexer-use-case.jpg
      url:      https://speakerdeck.com/odolbeau/doctrine-lexer-use-case
    elk-elasticsearch-logstash-kibana:
      authors:  [jb-favre]
      date:     "26-29 June"
      event:    "Pas Sage en Seine"
      place:    "Paris (France)"
      title:    "ELK - Elasticsearch, Logstash & Kibana"
      thumb:    jb-favre_elk-elasticsearch-logstash-kibana.jpg
      url:      https://blog-notes.jbfavre.org/?pses2014-elk-elasticsearch-logstash-amp-kibana,3047
    agility-in-your-translation-workflow:
      authors:  [matthieu-moquet]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "Agility in your translation workflow"
      thumb:    matthieu-moquet_phptour-2014-i18n.jpg
      url:      https://speakerdeck.com/mattketmo/agility-in-your-translation-workflow
    sso-and-soa:
      authors:  [matthieu-moquet]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "SSO & SOA"
      thumb:    matthieu-moquet_phptour-2014-sso-soa.jpg
      url:      https://speakerdeck.com/mattketmo/sso-and-soa
    debian-usage-at-blablacar:
      authors:  [jb-favre]
      date:     "4 June"
      event:    "Debian Meetup Paris"
      place:    "Paris (France)"
      title:    "Debian usage at BlaBlaCar"
      thumb:    jb-favre_debian-usage-at-blablacar-debian-paris-meetup.jpg
      url:      https://speakerdeck.com/jbfavre/debian-usage-at-blablacar-debian-paris-meetup
    swarrot-a-library-to-consume-them-all:
      authors:  [olivier-dolbeau]
      date:     "7-8 April"
      event:    "Symfony Live"
      place:    "Paris (France)"
      title:    "Swarrot, a library to consume them all"
      thumb:    olivier-dolbeau_swarrot-a-library-to-consume-them-all.jpg
      url:      https://speakerdeck.com/odolbeau/swarrot-a-library-to-consume-them-all
    making-asynchronous-tasks-in-php:
      authors:  [olivier-dolbeau]
      date:     "7-8 April"
      event:    "Symfony Live"
      place:    "Paris (France)"
      title:    "Making asynchronous tasks in PHP - The easy way"
      thumb:    olivier-dolbeau_making-asynchronous-tasks-in-php.jpg
      url:      https://speakerdeck.com/odolbeau/making-asynchronous-tasks-in-php
    decoupling-your-application:
      authors:  [matthieu-moquet]
      date:     "7-8 April"
      event:    "Symfony Live"
      place:    "Paris (France)"
      title:    "Decoupling your application"
      thumb:    matthieu-moquet_symfony-live-2014.jpg
      url:      https://speakerdeck.com/mattketmo/decoupling-your-application

url:            "http://blablatech.com"
