articletags:
  - application-architecture
  - conferences
  - culture
  - mobile
  - organisation
  - technology

authors:
  alexandra-tritz:
    name:       "Alexandra Tritz"
    nickname:   "Lexou"
    github:     "tritzalexandra"
    twitter:    "lexouthirteen"
    role:       "Mobile Development Engineer"
  benjamin-de-bernardi:
    name:       "Benjamin De Bernardi"
    nickname:   "Junior"
    github:     "genesor"
    twitter:    "Genes0r"
    role:       "Web Development Engineer"
  benjamin-fraud:
    name:       "Benjamin Fraud"
    nickname:   "bench1ps"
    github:     "bench1ps"
    twitter:    "bench1ps"
    role:       "Web Development Engineer"
  christian-jennewein:
    name:       "Christian Jennewein"
    nickname:   "Christian"
    twitter:    "cestcri"
    github:     "cestcri"
    role:       "Tech Manager"
  erwann-robin:
    name:       "Erwann Robin"
    nickname:   "Erwann"
    twitter:    "diwann"
    github:     "diwann"
    role:       "Mobile Development Engineer"
  fanny-gaborit:
    name:       "Fanny Gaborit"
    nickname:   "Fanny"
    twitter:    "fagaborit"
    github:
    role:       "Tech Manager"
  francis-nappez:
    name:       "Francis Nappez"
    nickname:   "Fnapz"
    twitter:    "fnapz"
    github:
    role:       "CTO"
  fx-oxeda:
    name:       "François-Xavier Oxeda"
    nickname:   "FX"
    twitter:    "DEIONaLiMs"
    github:     "DEIONaLiMs"
    role:       "Mobile Development Engineer"
  jb-favre:
    name:       "Jean-Baptiste Favre"
    nickname:   "JB"
    twitter:    "jbfavre"
    github:     "jbfavre"
    role:       "Web Architect"
  jerome-moussay:
    name:       "Jérôme Moussay"
    nickname:   "Jérôme"
    twitter:    "jmoussay"
    github:
    role:       "SEO Manager"
  loic-effner:
    name:       "Loïc Effner"
    nickname:   "Loïc"
    twitter:    "loiceffn"
    github:     "loiceffn"
    role:       "Mobile Development Engineer"
  matthieu-moquet:
    name:       "Matthieu Moquet"
    nickname:   "Mattketmo"
    github:     "MattKetmo"
    twitter:    "MattKetmo"
    role:       "Web Architect"
  mickael-rodrigues:
    name:       "Mickael Rodrigues"
    nickname:   "Mickael"
    github:
    twitter:
    role:       "Mobile Development Engineer"
  muriel-lusseau:
    name:       "Muriel Lusseau"
    nickname:   "Muriel"
    github:     "metalmumu"
    twitter:    "metalmumu"
    role:       "Web Development Engineer"
  nicolas-blanc:
    name:       "Nicolas Blanc"
    nickname:   "Jardin"
    twitter:    "thewhitegeek"
    github:
    role:       "Web Architect"
  nicolas-menoux:
    name:       "Nicolas Menoux"
    nickname:
    twitter:    "nickyinthecloud"
    github:
    role:       "Head of Data"
  nicolas-schwartz:
    name:       "Nicolas Schwartz"
    nickname:   "Nico"
    twitter:    "nicoschwartz"
    github:     "nicoschwartz"
    role:       "Tech Manager"
  nicolas-tricot:
    name:       "Nicolas Tricot"
    nickname:   "ShoLine"
    twitter:    "sholine42"
    github:     "sholine"
    role:       "Tech Manager"
  olivier-dolbeau:
    name:       "Olivier Dolbeau"
    nickname:   "Olivier"
    github:     "odolbeau"
    twitter:    "odolbeau"
    role:       "Web Architect"
  pierre-lemee:
    name:       "Pierre Lemée"
    nickname:   "Pierre"
    github:
    twitter:    "pitipout"
    role:       "Web Development Engineer"
  pierre-yves-lebecq:
    name:       "Pierre-Yves Lebecq"
    nickname:   "PY"
    github:     "pylebecq"
    twitter:    "pylebecq"
    role:       "Web Development Engineer"
  piotr-zarowny:
    name:       "Piotr Zarówny"
    nickname:   "Piotr"
    twitter:
    github:
    role:       "Tech Manager"
  remi-paulmier:
    name:       "Rémi Paulmier"
    nickname:   "Shtouff"
    twitter:    "shtouff"
    github:     "shtouff"
    role:       "tech leader"
  saad-bouchehboun:
    name:       "Saad Bouchehboun"
    nickname:
    github:
    twitter:
    role:       "Tech Manager"
  tony-fouchard:
    name:       "Tony Fouchard"
    nickname:   "Tony"
    github:
    twitter:    "hightoxicity"
    role:       "Web Architect"

description:    "Share More, Learn More — BlaBlaCar's Tech team"

gems:
  - jekyll-redirect-from
  - jekyll-paginate

highlighter:    pygments

markdown:       rdiscount

name:           "the BlaBlaTech Blog"

paginate:       10

permalink:      /blog/:title

talks:
  2015:
    benjamin-de-bernardi_symfonycon2015:
      authors:  [benjamin-de-bernardi, olivier-dolbeau]
      date:     "4 December"
      event:    "SymfonyCon 2015"
      place:    "Paris (France)"
      title:    "Symfony @ BlaBlaCar"
      thumb:    benjamin-de-bernardi_symfonycon2015.jpg
      url:      https://speakerdeck.com/genesor/symfony-at-blablacar
    alexandra-tritz_appdays-2015:
      authors:  [alexandra-tritz]
      date:     "26 November"
      event:    "appdays 2015"
      place:    "Paris (France)"
      title:    "Analytics & Monitoring at BlaBlaCar"
      thumb:    alexandra-tritz_appdays-2015.jpg
      url:      https://speakerdeck.com/alexandratritz/analytics-and-monitoring-at-blablacar
    loic_effner_appdays-2015:
      authors:  [loic-effner]
      date:     "26 November"
      event:    "appdays 2015"
      place:    "Paris (France)"
      title:    "Manage Apps at Home"
      thumb:    loic_effner_appdays-2015.jpg
      url:      https://speakerdeck.com/loiceffn/manage-apps-remotely
    hacking-in-the-name-of-ride-sharing:
      authors:  [pierre-lemee]
      date:     "23 November"
      event:    "La Manche Open School Promotion #1"
      place:    "Granville (France)"
      title:    "Hacking in the name of ride-sharing"
      thumb:    pierre-lemee_hacking-in-the-name-of-ride-sharing.png
      url:      /talks/pierre-lemee_hacking-in-the-name-of-ride-sharing.pdf
    forumphp2015-matthieu:
      authors:  [matthieu-moquet]
      date:     "23-24 November"
      event:    "ForumPHP 2015"
      place:    "Montrouge (France)"
      title:    "Un éléphant dans le monde des licornes"
      thumb:    matthieu-moquet_forumphp-2015.jpg
      url:      https://speakerdeck.com/mattketmo/forumphp-2015
    phpcon-poland-2015_the-technical-story-of-blablacar:
      authors:  [benjamin-de-bernardi, olivier-dolbeau]
      date:     "13-15 November"
      event:    "PHPCon Poland 2015"
      place:    "Ossa (Poland)"
      title:    "The technical story of BlaBlaCar"
      thumb:    benjamin-de-bernardi_phpcon-poland-2015_the-technical-story-of-blablacar.jpg
      url:      https://speakerdeck.com/genesor/phpcon-2015-the-technical-story-of-blablacar
    phpcon-poland-2015_monolog:
      authors:  [olivier-dolbeau]
      date:     "13-15 November"
      event:    "PHPCon Poland 2015"
      place:    "Ossa (Poland)"
      title:    "When monolog meets ELK (& bermudas!)"
      thumb:    olivier-dolbeau_phpcon-2015-elk.jpg
      url:      https://speakerdeck.com/odolbeau/when-monolog-meets-elk-and-bermudas
    phpcon-poland-2015_cqrs-event-sourcing:
      authors:  [matthieu-moquet]
      date:     "13-15 November"
      event:    "PHPCon Poland 2015"
      place:    "Ossa (Poland)"
      title:    "CQRS & Event Sourcing"
      thumb:    matthieu-moquet_phpcon-poland-2015_cqrs.jpg
      url:      https://speakerdeck.com/mattketmo/cqrs-and-event-sourcing
    trello-meetup-2015:
      authors:  [nicolas-tricot]
      date:     "27 October"
      event:    "1er Meetup Trello French UG"
      place:    "Paris (France)"
      title:    "Workflow and project management with Trello @ BBC"
      thumb:    nicolas-tricot_trello-meetup-2015.jpg
      url:      /talks/nicolas-tricot_trello-meetup-2015.pdf
    blablatech-warsaw-meetup-2-2015-junior:
      authors:  [benjamin-de-bernardi]
      date:     "20 October"
      event:    "BlaBlaTech Warsaw Meetup #2"
      place:    "Warsaw (Poland)"
      title:    "Gateway - How to bring down our monolith"
      thumb:    benjamin-de-bernardi_gateway-bring-down-your-monolith.jpg
      url:      https://speakerdeck.com/genesor/gateway-how-to-bring-down-our-monolith
    blablatech-warsaw-meetup-2-2015-olivier:
      authors:  [olivier-dolbeau]
      date:     "20 October"
      event:    "BlaBlaTech Warsaw Meetup #2"
      place:    "Warsaw (Poland)"
      title:    "Swarrot, a library to consume them all!"
      thumb:    olivier-dolbeau_blablatech-warsaw-meetup-2.jpg
      url:      https://speakerdeck.com/odolbeau/swarrot-a-library-to-consume-them-all-1
    lean-it-summit-2015:
      authors:  [christian-jennewein, nicolas-tricot]
      date:     "8-9 October"
      event:    "Lean IT Summit"
      place:    "Paris (France)"
      title:    "Organising BlaBlaTech"
      thumb:    christian-jennewein_lean-it-summit-2015.jpg
      url:      https://speakerdeck.com/cestcri/organising-blablatech-at-lean-it-summit
    paris-web-2015:
      authors:  [benjamin-de-bernardi, olivier-dolbeau]
      date:     "2 October"
      event:    "Paris Web"
      place:    "Montrouge (France)"
      title:    "Slicing up a monolithic application Why and how?"
      thumb:    olivier-dolbeau_slicing-up-a-monolithic-application-why-and-how.jpg
      url:      https://speakerdeck.com/odolbeau/slicing-up-a-monolithic-application-why-and-how
    sfpot-nantes-2015:
      authors:  [olivier-dolbeau]
      date:     "28 September"
      event:    "sfPot Nantes #1"
      place:    "Paris (France)"
      title:    "Symfony2 killed me!"
      thumb:    olivier-dolbeau_sfpot-nantes-2015.jpg
      url:      https://speakerdeck.com/odolbeau/symfony2-killed-me
    zabbix-2015:
      authors:  [jb-favre]
      date:     "11-12 September"
      event:    "Zabbix Conference 2015"
      place:    "Riga (Latvia)"
      title:    "How we monitor 1 billion km of monthly ride sharing"
      thumb:    jp-favre_zabbix-2015.jpg
      url:      https://speakerdeck.com/jbfavre/monitoring-a-billion-kilometers-of-monthly-ride-sharing-at-blablacar-zabbix-conference-2015
      video:    https://www.youtube.com/watch?v=bgwSFjKT3FE
    ipc-berlin-2015-logs:
      authors:  [matthieu-moquet]
      date:     "7-11 June"
      event:    "IPC Berlin 2015"
      place:    "Berlin (Germany)"
      title:    "Take care of your logs with ELK"
      thumb:    matthieu-moquet-ipc-berlin-2015-elk.jpg
      url:      https://speakerdeck.com/mattketmo/take-care-of-your-logs-with-elk
    ipc-berlin-2015_technical-story:
      authors:  [matthieu-moquet]
      date:     "7-11 June"
      event:    "IPC Berlin 2015"
      place:    "Berlin (Germany)"
      title:    "From 1 to 20 million users the technical story of BlaBlaCar"
      thumb:    matthieu-moquet_ipc-berlin-2015-technical-story.jpg
      url:      https://speakerdeck.com/mattketmo/from-1-to-20-million-users-the-technical-story-of-blablacar
    paris-monitoring-meetup-2015:
      authors:  [jb-favre]
      date:     "4 June"
      event:    "Paris Monitoring Meetup #1"
      place:    "Paris (France)"
      title:    "Zabbix chez BlaBlaCar"
      thumb:    jb-favre_zabbix-at-blablacar.png
      url:      https://blog.jbfavre.org/2015/06/05/paris-monitoring-meetup-zabbix-chez-blablacar/
    blablatech-warsaw-meetup-1-2015:
      authors:  [christian-jennewein, nicolas-tricot, piotr-zarowny]
      date:     "28 May"
      event:    "BlaBlaTech Warsaw Meetup #1"
      place:    "Warsaw (Poland)"
      title:    "BlaBlaTech @ Warsaw"
      thumb:    christian-jennewein_blablatech-warsaw.jpg
      url:      https://speakerdeck.com/cestcri/blablatech-at-warsaw
    phptour-luxembourg-2015:
      authors:  [matthieu-moquet]
      date:     "13 May"
      event:    "PHPTour 2015"
      place:    "Luxembourg (Luxembourg)"
      title:    "Event Sourcing"
      thumb:    matthieu-moquet_phptour2015.jpg
      url:      https://speakerdeck.com/mattketmo/event-sourcing
    devopsdays-2015:
      authors:  [muriel-lusseau, nicolas-blanc]
      date:     "14-15 April"
      event:    "DevOps Days"
      place:    "Paris (France)"
      title:    "DevOps Culture at BlaBlaCar - Keep CAMS and grow"
      thumb:    nicolas-blanc_devopsdays-2015.jpg
      url:      nicolas-blanc_devopsdays-2015.pdf
      video:    http://www.dailymotion.com/video/x2n9etn
    sflive-2015-olivier:
      authors:  [olivier-dolbeau]
      date:     "9 April"
      event:    "Symfony Life 2015"
      place:    "Paris (France)"
      title:    "Logs hunting"
      thumb:    olivier-dolbeau_sflive-2015.jpg
      url:      https://speakerdeck.com/odolbeau/logs-hunting
    scrumday-2015:
      authors:  [christian-jennewein, nicolas-tricot]
      date:     "2-3 April"
      event:    "ScrumDay 2015"
      place:    "Disneyland (France)"
      title:    "Scrum @ BlaBlaTech"
      thumb:    christian-jennewein_scrumday-2015.jpg
      url:      https://speakerdeck.com/cestcri/scrum-at-blablatech
    paris-tech-talk-9:
      authors:  [olivier-dolbeau]
      date:     "24 March"
      event:    "Paris Tech Talk #9"
      place:    "Paris (France)"
      title:    "Don't let your log go away"
      thumb:    olivier-dolbeau_paris-tech-talk-9.jpg
      url:      https://speakerdeck.com/odolbeau/dont-let-your-log-go-away
    sfpot_mars-2015:
      authors:  [olivier-dolbeau]
      date:     "17 March"
      event:    "sfPot Mars 2015"
      place:    "Paris (France)"
      title:    "Microservices @ BlaBlaCar"
      thumb:    olivier-dolbeau_sfpot-nantes.jpg
      url:      https://speakerdeck.com/odolbeau/microservices-at-blablacar
    paug-2015-03:
      authors:  [alexandra-tritz, fx-oxeda, saad-bouchehboun]
      date:     "3 March"
      event:    "PAUG"
      place:    "Paris (France)"
      title:    "Développer une app Android en 2015"
      thumb:    paug-2015-03.png
      url:      https://speakerdeck.com/alexandratritz/developper-une-app-android-en-2015
  2014:
    symfonycon-2014:
      authors:  [matthieu-moquet]
      date:     "27-29 November"
      event:    "SymfonyCon"
      place:    "Madrid (Spain)"
      title:    "Localization should not be a pain (anymore)"
      thumb:    matthieu-moquet_symfonycon-2014.jpg
      url:      https://speakerdeck.com/mattketmo/localization-should-not-be-a-pain-anymore
    appdays-2014:
      authors:  [erwann-robin, fx-oxeda]
      date:     "6-7 November"
      event:    "appdays"
      place:    "Paris (France)"
      title:    "Comment migrer 10 millions de membres d’une webview vers une app native ?"
      thumb:    erwann-robin_appdays-2014.jpg
      url:      /talks/erwann-robin_appdays-2014.pdf
    elasticsearch-feedback:
      authors:  [nicolas-blanc, olivier-dolbeau]
      date:     "25 September"
      event:    "Meetup Elasticsearch France #9"
      place:    "Paris (France)"
      title:    "ElasticSearch feedback"
      thumb:    nicolas-blanc_elasticsearch-feedback.png
      url:      /talks/nicolas-blanc_elasticsearch-feedback.odp
    laisse-pas-trainer-ton-log:
      authors:  [olivier-dolbeau]
      date:     "23-24 October"
      event:    "Forum PHP"
      place:    "Montrouge (France)"
      title:    "Laisse pas trainer ton log"
      thumb:    olivier-dolbeau_laisse-pas-trainer-ton-log.jpg
      url:      https://speakerdeck.com/odolbeau/laisse-pas-trainer-ton-log
    when-monolog-meet-elk:
      authors:  [olivier-dolbeau]
      date:     "15 July"
      event:    "sfPot"
      place:    "Paris (France)"
      title:    "When Monolog meet ELK"
      thumb:    olivier-dolbeau_when-monolog-meet-elk.jpg
      url:      https://speakerdeck.com/odolbeau/when-monolog-meet-elk
    asynchronous-tasks-in-php:
      authors:  [olivier-dolbeau]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "Asynchronous tasks in PHP"
      thumb:    olivier-dolbeau_asynchronous-tasks-in-php.jpg
      url:      https://speakerdeck.com/odolbeau/asynchronous-tasks-in-php
    doctrine-lexer-use-case:
      authors:  [olivier-dolbeau]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "Doctrine Lexer use case"
      thumb:    olivier-dolbeau_doctrine-lexer-use-case.jpg
      url:      https://speakerdeck.com/odolbeau/doctrine-lexer-use-case
    elk-elasticsearch-logstash-kibana:
      authors:  [jb-favre]
      date:     "26-29 June"
      event:    "Pas Sage en Seine"
      place:    "Paris (France)"
      title:    "ELK - Elasticsearch, Logstash & Kibana"
      thumb:    jb-favre_elk-elasticsearch-logstash-kibana.jpg
      url:      https://blog-notes.jbfavre.org/?pses2014-elk-elasticsearch-logstash-amp-kibana,3047
    agility-in-your-translation-workflow:
      authors:  [matthieu-moquet]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "Agility in your translation workflow"
      thumb:    matthieu-moquet_phptour-2014-i18n.jpg
      url:      https://speakerdeck.com/mattketmo/agility-in-your-translation-workflow
    sso-and-soa:
      authors:  [matthieu-moquet]
      date:     "23-24 June"
      event:    "PHP Tour"
      place:    "Lyon (France)"
      title:    "SSO & SOA"
      thumb:    matthieu-moquet_phptour-2014-sso-soa.jpg
      url:      https://speakerdeck.com/mattketmo/sso-and-soa
    debian-usage-at-blablacar:
      authors:  [jb-favre]
      date:     "4 June"
      event:    "Debian Meetup Paris"
      place:    "Paris (France)"
      title:    "Debian usage at BlaBlaCar"
      thumb:    jb-favre_debian-usage-at-blablacar-debian-paris-meetup.jpg
      url:      https://speakerdeck.com/jbfavre/debian-usage-at-blablacar-debian-paris-meetup
    swarrot-a-library-to-consume-them-all:
      authors:  [olivier-dolbeau]
      date:     "7-8 April"
      event:    "Symfony Live"
      place:    "Paris (France)"
      title:    "Swarrot, a library to consume them all"
      thumb:    olivier-dolbeau_swarrot-a-library-to-consume-them-all.jpg
      url:      https://speakerdeck.com/odolbeau/swarrot-a-library-to-consume-them-all
    making-asynchronous-tasks-in-php:
      authors:  [olivier-dolbeau]
      date:     "7-8 April"
      event:    "Symfony Live"
      place:    "Paris (France)"
      title:    "Making asynchronous tasks in PHP - The easy way"
      thumb:    olivier-dolbeau_making-asynchronous-tasks-in-php.jpg
      url:      https://speakerdeck.com/odolbeau/making-asynchronous-tasks-in-php
    decoupling-your-application:
      authors:  [matthieu-moquet]
      date:     "7-8 April"
      event:    "Symfony Live"
      place:    "Paris (France)"
      title:    "Decoupling your application"
      thumb:    matthieu-moquet_symfony-live-2014.jpg
      url:      https://speakerdeck.com/mattketmo/decoupling-your-application

url:            "http://blablatech.com"
